# Generated by Django 5.1.7 on 2025-03-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hid', models.CharField(max_length=255, unique=True)),
                ('conversation', models.JSONField(default=dict)),
            ],
        ),
    ]
