# Generated by Django 5.1.7 on 2025-03-22 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosedDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to='card.chathistory')),
            ],
        ),
    ]
